### ISSUE TITLE
Declarations file should use lowercase `typestate`

### ISSUE THREAD

**Issue by kamranayub** [eonarheim/TypeState#9]
I installed TypeState into my Node.js project for VS and when I copied the declarations file over, it failed to import:

```ts
import TypeState = require('typestate')
```

Because the declared module name `TypeState` doesn't match the npm module name, lowercase `typestate`.

Would be best if TypeState used the lowercase version by default but I fixed it easily by fixing the module declaration in typestate.d.ts.

```ts
declare module "typestate"
```

**Comment by jan-molak** [comment]
Hey @kamranayub, I'm facing the same problem. It seems like you know how to address it so perhaps you'd like to submit a pull request and help @eonarheim get a new release out? 😄

**Comment by eonarheim** [comment]
I can probably get to this later tonight or tomorrow, should be a
relatively simple fix. ;)

**Comment by jan-molak** [comment]
Awesome, thanks for the quick response @eonarheim! Looking forward to it 👍

**Comment by eonarheim** [comment]
So this code definitely works, but I have some problems with it because of the way I'm poly-filling the 'exports' variable in order to work both in node and the browser. The TypeScript compiler doesn't like it, and to be fair it is a bit of a hack so I'm forcing build even on tsc compile errors.

This turned out to be slightly more difficult than I had anticipated :wink: but that is software estimation for you.

I'm going to try and come up with a good way of allowing TypeState to work both in node and in the browser in a way that is backwards compatible. I'll take a look as some other libraries to see how they deal with this.

**Comment by jan-molak** [comment]
Haha, no worries! Thanks for taking your time to look into this 👍

**Comment by paralin** [comment]
Can someone figure out how to fix this? I'm still getting these errors related to the capitalization

**Comment by eonarheim** [comment]
Hi Christian! This dropped off my radar thanks for the poke, I'll take a
look again later.

Right now there is a build that "works" from a casing and backwards
compatibility sense but it throws typescript compiler errors which feels
bad. Perhaps it's better to break backwards compatibility with regards to
casing for a cleaner build going forward... perhaps not.

**Comment by paralin** [comment]
Is there some kind of temporary solution I can use?

**Comment by eonarheim** [comment]
@kamranayub may have a work around that he used. I think he lowercased
declaration in his typestate.d.ts

Correct me if I'm wrong

**Comment by kamranayub** [comment]
Yeah, I copied the declaration file to my project (to keep in source control) and just renamed the module inside the `.d.ts` file.

**Comment by eonarheim** [comment]
Hey @kamranayub @paralin @jan-molak 

Take a look at my self PR for #13 as a fix for this.

In order to make this work (and feel good about it) I've created a separate file that is generated for node users `typestate-node.js` which is what folks should use going forward in node.

I want to make sure I'm tracking with your needs in TypeState :) thanks for your patience and feedback!
